### ISSUE TITLE
exec format error

### ISSUE THREAD

**Issue by jerome-pilotin** [StephenMiracle/wordpress-docker-frankenphp#3]
Hi,

I've tried your compose file on a newly installed RockyLinux 9 server, and I'm getting the following error (repeated until exit) after launching it:

```
wordpress-1    | exec /usr/local/bin/docker-entrypoint.sh: exec format error
```

(Both the image and the server are amd64 so AFAIK it's not a platform mismatch)

I've pulled [your image](https://github.com/StephenMiracle/frankenwp/blob/main/Dockerfile) and tried to build it locally, and I'm now getting that error:

```
 => ERROR [base  3/22] RUN apt-get update && apt-get install -y --no-install-recommends     ca-certificates  0.3s
------
 > [base  3/22] RUN apt-get update && apt-get install -y --no-install-recommends     ca-certificates     ghostscript     curl     libonig-dev     libxml2-dev     libcurl4-openssl-dev     libssl-dev     libzip-dev     unzip     git     libmagickwand-dev     libjpeg-dev     libwebp-dev     libzip-dev     libmagickcore-dev     libmagickwand-6.q16-6     libmagickcore-6.q16-6     libmemcached-dev     zlib1g-dev:
0.231 exec /bin/sh: exec format error
------
Dockerfile:25
--------------------
  24 |
  25 | >>> RUN apt-get update && apt-get install -y --no-install-recommends \
  26 | >>>     ca-certificates \
  27 | >>>     ghostscript \
  28 | >>>     curl \
  29 | >>>     libonig-dev \
  30 | >>>     libxml2-dev \
  31 | >>>     libcurl4-openssl-dev \
  32 | >>>     libssl-dev \
  33 | >>>     libzip-dev \
  34 | >>>     unzip \
  35 | >>>     git \
  36 | >>>     libmagickwand-dev \
  37 | >>>     libjpeg-dev \
  38 | >>>     libwebp-dev \
  39 | >>>     libzip-dev \
  40 | >>>     libmagickcore-dev \
  41 | >>>     libmagickwand-6.q16-6 \
  42 | >>>     libmagickcore-6.q16-6 \
  43 | >>>     libmemcached-dev \
  44 | >>>     zlib1g-dev
  45 |
--------------------
ERROR: failed to solve: process "/bin/sh -c apt-get update && apt-get install -y --no-install-recommends     ca-certificates     ghostscript     curl     libonig-dev     libxml2-dev     libcurl4-openssl-dev     libssl-dev     libzip-dev     unzip     git     libmagickwand-dev     libjpeg-dev     libwebp-dev     libzip-dev     libmagickcore-dev     libmagickwand-6.q16-6     libmagickcore-6.q16-6     libmemcached-dev     zlib1g-dev" did not complete successfully: exit code: 1
```

What am I doing wrong? Can I provide you with more info to help you debug this?

EDIT: Oh sh*t, just now seeing line 6 from the Dockerfile...

EDIT2: So obviously now with that line edited the image builds successfully and now the error resides in the binary format of the frankenphp executable. I suppose this can be solved with Dockerfile.builder but I am not familiar with that at all

**Comment by StephenMiracle** [comment]
Hey! I'll check it out today. I did separate the builder because it is a much longer process and not needed for just getting the Wordpress to run.

**Comment by StephenMiracle** [comment]
You shouldn't have any issue with the builder at this point. It's odd that its failing on the basic linux package installs.

My local is amd64 and I run it here. Then I run it using arm on AWS .


I haven't used RockyLinux so I'll investigate that.

**Comment by StephenMiracle** [comment]
Hey @jerome-pilotin , I started an Rocky Linux 9 on AWS and am able to recreate. Since this issue relates to the Docker image, I recreated the ticket here to track: https://github.com/StephenMiracle/frankenwp/issues/3

Going to close this ticket feel free to comment and follow on the other one.

Thanks!
